
services:
  mongo:
    image: mongo:latest
    container_name: hockey-cms-mongo
    ports:
      - '27017:27017'
    environment:
      # These variables create the root user on first launch
      MONGO_INITDB_ROOT_USERNAME: root-admin
      MONGO_INITDB_ROOT_PASSWORD: fun4fly # <-- Replace this!
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: