version: '3'

services:
  # This service runs the MongoDB database in a container.
  # It's the only service needed for local development.
  mongo:
    image: mongo:latest
    container_name: payload-mongo-db
    ports:
      - '27017:27017'
    restart: unless-stopped
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
